name: ✨ Feature
description: Sugira uma nova funcionalidade
title: "[MÓDULO]: [RECURSO]: [Descrição simples sobre a feature] "
labels: ["feature"]
body:
  - type: dropdown
    attributes:
      label: Tipo de Feature
      options:
        - "back-end"
        - "front-end"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Descrição
      description: "Descreva a feature que você irá implementar."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Controle de Versão"
      options:
        - label: "Está implementando um novo recurso?"
          required: false